# caps-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caps
  template:
    metadata:
      labels:
        app: caps
    spec:
      containers:
        - name: caps-api
          image: your-registry/caps-api:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: caps-service
spec:
  selector:
    app: caps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001

