# trousers-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trousers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trousers
  template:
    metadata:
      labels:
        app: trousers
    spec:
      containers:
        - name: trousers-api
          image: your-registry/trousers-api:latest
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: trousers-service
spec:
  selector:
    app: trousers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
